aufs: bugfix, added #include <linux/vmalloc.h> in fs/aufs/super.c
(Uli Middelberg via github)
I needed to add this include, otherwise compiling super.c on ARMv7 fails
with the following error:
`error: implicit declaration of function 'vzalloc'`

(Okajima)
The line was there until this Monday's release. I removed it without
thinking much.
The patch will be merged and release in next release. But the copyright
sentences are included by aufs3-standalone.git only. For
aufs3-linux.git, it will be removed.

Signed-off-by: Uli Middelberg <uli@middelberg.de>
Signed-off-by: J. R. Okajima <hooanon05g@gmail.com>
(cherry picked from commit e6401106a1c7035a381d3a685cde0864e0ea694c)